#!/usr/bin/env rust-script
//! ```cargo
//! [package]
//! edition = "2021"
//!
//! [dependencies]
//! anyhow = "1.0.99"
//! clap = { version = "4.5.45", features = ["derive"] }
//! flate2 = "1.1.2"
//! reqwest = { version = "0.12.28", default-features = false, features = ["blocking", "json", "rustls-tls"] }
//! serde = { version = "1.0.219", features = ["derive"] }
//! serde_json = "1.0.143"
//! sha2 = "0.10.9"
//! uuid = { version = "1.18.0", features = ["serde"] }
//! ```
//!
//! Emit the SS5 **artpack** table, `kind=uuid-scheme`: one Scryfall printing
//! UUID per catalog id, in the shared self-verifying TSV envelope.
//!
//! Normative format: `docs/CARD_SKIN_FORMATS.md` in the DeepScry repository
//! (ds-5432). An artpack is a URL-MAPPING table, not an image archive: the
//! table stores opaque per-printing UUIDs, and the client computes the image
//! URL with the layout function declared in the header
//! (`layout=scryfall-cdn-v1`:
//! `<base_url>/<size>/front/<a>/<b>/<uuid>.<ext>`, the same computation as
//! the `card-compiler` crate's `cardskin::cdn_image_url_with`). No card name
//! ever crosses the wire — this is the sanctioned image pipeline.
//!
//! Printing selection per Oracle identity mirrors the established policy of
//! DeepScry's `build-card-lookup` art index (`card-compiler`'s builder):
//! prefer a non-art-series printing with a real image over digital-only
//! printings, then the OLDEST `released_at`, with the lexicographically
//! smallest printing UUID as the final tie-break so the output is fully
//! deterministic regardless of snapshot ordering. Coverage may be sparse
//! (an id whose identity has no usable image simply has no row); every
//! missing id is reported on stderr, never silently dropped.

use anyhow::{bail, Context, Result};
use clap::Parser;
use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;
use uuid::Uuid;

#[path = "lib/cas.rs"]
mod cas;
#[path = "../lib/scryfall_bulk.rs"]
mod scryfall_bulk;

const LAYOUT: &str = "scryfall-cdn-v1";
const BASE_URL: &str = "https://cards.scryfall.io";
const EXT: &str = "jpg";

#[derive(Parser, Debug)]
#[command(about = "Emit the kind=uuid-scheme artpack TSV (SS5) from the Scryfall snapshot and print its CID")]
struct Args {
    /// Unified numeric identity catalog (`#id`, `kind`, `oracle_id`).
    #[arg(long)]
    catalog: PathBuf,

    /// Decompressed Scryfall default_cards cache.
    #[arg(long, default_value = ".cache/scryfall/default_cards.json")]
    cache: PathBuf,

    /// The SHA-256 of the exact supplied identity catalog.
    #[arg(long)]
    catalog_identity: String,

    /// Verify this existing table against freshly generated bytes instead of
    /// publishing `--output`.
    #[arg(long)]
    verify: Option<PathBuf>,

    /// Output table.
    #[arg(long, default_value = "presentation/artpack_scryfall_uuid.tsv")]
    output: PathBuf,

    /// Ignore a present cache and download the current snapshot.
    #[arg(long)]
    refresh: bool,
}

/// Everything selection needs about one candidate printing.
#[derive(Clone, Debug)]
struct Candidate {
    printing_id: Uuid,
    released_at: String,
    art_series: bool,
    real_image: bool,
    digital: bool,
    english: bool,
}

impl Candidate {
    /// Higher ranks first; mirrors `card-compiler`'s builder policy with an
    /// added English-language preference (default_cards includes printings
    /// that only exist in one non-English language).
    fn rank(&self) -> (bool, bool, bool, bool) {
        (!self.art_series, self.real_image, !self.digital, self.english)
    }

    fn better_than(&self, other: &Candidate) -> bool {
        match self.rank().cmp(&other.rank()) {
            std::cmp::Ordering::Greater => true,
            std::cmp::Ordering::Less => false,
            std::cmp::Ordering::Equal => match self.released_at.cmp(&other.released_at) {
                std::cmp::Ordering::Less => true,
                std::cmp::Ordering::Greater => false,
                std::cmp::Ordering::Equal => self.printing_id < other.printing_id,
            },
        }
    }
}

fn main() -> Result<()> {
    let args = Args::parse();
    if args.catalog_identity.len() != 64
        || !args
            .catalog_identity
            .bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
    {
        bail!("--catalog-identity must be a lowercase hex SHA-256");
    }

    let catalog_bytes = fs::read(&args.catalog).with_context(|| format!("read {}", args.catalog.display()))?;
    let actual_identity = cas::sha256_hex(&catalog_bytes);
    if args.catalog_identity != actual_identity {
        bail!(
            "--catalog-identity is {}, but {} hashes to {actual_identity}; refusing a stale stamp",
            args.catalog_identity,
            args.catalog.display()
        );
    }
    let catalog = parse_catalog(&catalog_bytes)?;
    scryfall_bulk::ensure_cache(&args.cache, args.refresh)?;

    // Best candidate per Oracle identity.
    let wanted: std::collections::HashSet<Uuid> = catalog.values().copied().collect();
    let mut best: BTreeMap<Uuid, Candidate> = BTreeMap::new();
    scryfall_bulk::for_each_card(&args.cache, |card| {
        let Some(oracle_id) = card.effective_oracle_id() else {
            return;
        };
        if !wanted.contains(&oracle_id) {
            return;
        }
        let Some(printing_id) = card.id else {
            return;
        };
        let has_image_uris = card.image_uris.is_some() || card.card_faces.iter().any(|face| face.image_uris.is_some());
        let real_image =
            has_image_uris && !matches!(card.image_status.as_deref(), Some("missing") | Some("placeholder"));
        let candidate = Candidate {
            printing_id,
            released_at: card.released_at.clone(),
            art_series: card.layout == "art_series",
            real_image,
            digital: card.digital,
            english: card.lang == "en",
        };
        match best.get(&oracle_id) {
            Some(current) if !candidate.better_than(current) => {}
            _ => {
                best.insert(oracle_id, candidate);
            }
        }
    })?;

    let mut body = String::new();
    let mut rows = 0usize;
    let mut missing: Vec<u32> = Vec::new();
    for (id, oracle_id) in &catalog {
        match best.get(oracle_id) {
            Some(candidate) if candidate.real_image => {
                body.push_str(&format!("{id}\t{}\n", candidate.printing_id));
                rows += 1;
            }
            _ => missing.push(*id),
        }
    }
    if rows == 0 {
        bail!("no catalog id resolved to a printing with a real image; refusing to emit an empty artpack");
    }
    if !missing.is_empty() {
        eprintln!(
            "WARNING: {} catalog id(s) have no usable image and are omitted (sparse coverage is legal): {}{}",
            missing.len(),
            missing
                .iter()
                .take(20)
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(", "),
            if missing.len() > 20 { ", …" } else { "" },
        );
    }

    let header_line = format!(
        "#id\tuuid\tmetadata: v=1 kind=uuid-scheme layout={LAYOUT} base_url={BASE_URL} ext={EXT} \
         catalog_identity={} cards={rows} source=scryfall license=scryfall-image-guidelines body_sha256={}\n",
        args.catalog_identity,
        cas::sha256_hex(body.as_bytes()),
    );
    let mut document = header_line.into_bytes();
    document.extend_from_slice(body.as_bytes());

    if let Some(path) = args.verify.as_deref() {
        let existing = fs::read(path).with_context(|| format!("read artpack {}", path.display()))?;
        if existing != document {
            bail!(
                "{} does not match the freshly generated, catalog-stamped artpack",
                path.display()
            );
        }
        eprintln!("Verified {}", path.display());
    } else if let Some(parent) = args.output.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
        let temporary = args.output.with_extension("write-part");
        fs::write(&temporary, &document).with_context(|| format!("write {}", temporary.display()))?;
        fs::rename(&temporary, &args.output).with_context(|| format!("publish {}", args.output.display()))?;
        eprintln!("Wrote {}", args.output.display());
    } else {
        bail!("output path {} has no parent", args.output.display());
    }

    println!("artpack_cid={}", cas::cid_for_bytes(&document));
    println!("artpack_size={}", document.len());
    println!("rows={rows}");
    println!("missing={}", missing.len());
    Ok(())
}

/// Dense unified catalog, reduced to its card `id → oracle_id` rows. Token
/// rows are validated but deliberately absent from a Scryfall image artpack.
fn parse_catalog(bytes: &[u8]) -> Result<BTreeMap<u32, Uuid>> {
    let text = std::str::from_utf8(bytes).context("catalog is not UTF-8")?;
    let mut lines = text.lines();
    let header = lines.next().context("catalog has no header row")?;
    let columns: Vec<&str> = header.split('\t').collect();
    let id_column = columns
        .iter()
        .position(|c| *c == "#id")
        .context("catalog header has no #id column")?;
    let oracle_column = columns
        .iter()
        .position(|c| *c == "oracle_id")
        .context("catalog header has no oracle_id column")?;
    let kind_column = columns
        .iter()
        .position(|c| *c == "kind")
        .context("catalog header has no kind column")?;
    let mut rows = BTreeMap::new();
    let mut expected = 0u32;
    for (offset, line) in lines.enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let line_number = offset + 2;
        let fields: Vec<&str> = line.split('\t').collect();
        let id: u32 = fields
            .get(id_column)
            .with_context(|| format!("catalog line {line_number} has no #id"))?
            .parse()
            .with_context(|| format!("catalog line {line_number} has a non-numeric #id"))?;
        expected += 1;
        if id != expected {
            bail!("catalog is not dense: expected id {expected} at line {line_number}, found {id}");
        }
        let oracle = fields
            .get(oracle_column)
            .with_context(|| format!("catalog line {line_number} has no oracle_id"))?;
        let kind = fields
            .get(kind_column)
            .with_context(|| format!("catalog line {line_number} has no kind"))?;
        match *kind {
            "card" => {
                let oracle_id = oracle
                    .parse()
                    .with_context(|| format!("catalog line {line_number} has an invalid card oracle_id"))?;
                rows.insert(id, oracle_id);
            }
            "token" if oracle.is_empty() => {}
            "token" => bail!("catalog line {line_number} is a token with a non-empty oracle_id"),
            other => bail!("catalog line {line_number} has unknown kind {other:?}"),
        }
    }
    if rows.is_empty() {
        bail!("catalog has no card rows");
    }
    Ok(rows)
}
